# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21a1d1e79652b65ec6019efbf90197a543479220f8b9fe461bf5affb271f9657e3d11c3aff989f69d6073bbf3df06b4be68f52bcc83259d300cf5a2545078605

test:
  secret_key_base: 6144594adbca6b6eabb730e90bd5efb45b301ad63947258bc3240ebf41928d4591e9f4b5817cf017bf4e91fd32eb1d524955e84fa1d39711d09cb3a697a7ebe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
